### ISSUE TITLE
Fix(QR code): Uncaught Error: code length overflow.

### ISSUE THREAD

**Issue by LifeAdventurer** [LifeAdventurer/patient-input-output-recorder#69]
![image](https://github.com/user-attachments/assets/eba574a7-e3bc-4149-8051-0eb88a81cf99)

**Comment by tobiichi3227** [comment]
⬆️
饕餮
囹圄
龍行龘龘

**Comment by LifeAdventurer** [comment]
https://github.com/kazuhikoarase/qrcode-generator
